### ISSUE TITLE
Issue Instantiating FeatureEngine Transformers

### ISSUE THREAD

**Issue by chris-santiago** [elisim/hydra-sklearn-pipelines#3]
# Issue
I ran into an issue using your config and func to instantiate a pipeline of [Feature-engine](https://feature-engine.trainindata.com/en/latest/index.html) transformers.  Those transformers do a strict type check during the `__init__` method, which raised errors with `DictConfig` and `ListConfig` objects. 

My initial attempt to resolve used hydra's `_convert_='partial'` method, but then I ran into some other issues with subscripting, getting items and proper instantiation of the individual pipeline components.

Posting resolution in case anyone that stumbles upon your repo/article runs into similar issue.

# Resolution

Modified `make_pipeline`:

```python
def make_pipeline(step_cfg: omegaconf.ListConfig):
    steps = hydra.utils.instantiate(step_cfg, _convert_='partial')
    return sklearn.pipeline.Pipeline([(name, tfm) for s in steps for name, tfm in s.items()])
```

still using your config format:

```yaml
preprocessor:
    _target_: demo.utils.make_pipeline
    step_cfg:
      - DropFeatures:
          _target_: feature_engine.selection.DropFeatures
          features_to_drop: ${features.drop}
      - StringImpute:
          _target_: feature_engine.imputation.CategoricalImputer
          fill_value: XX
          variables: ${features.string}
      - OrdinalEncoder:
          _target_: feature_engine.encoding.OrdinalEncoder
          variables: ${features.cat}
```

and finally instantiating in the same way:

```python
pipe = hydra.utils.instantiate(cfg.preprocessor, _recursive_=False)
```
